### ISSUE TITLE
How to log in to micropub

### ISSUE THREAD

**Issue by halojoy** [TomboFry/microlight#31]
I gave this a try.
After fixing the ROOT to correct setting
I could get to the first page alright.
But when I go to 'micropub' I get the error 'unauthorized'

How to log in?

**Comment by TomboFry** [comment]
To log in to micropub you need to log in using a micropub client which authenticates you with an IndieAuth server. For example - now that you have your server set up, try going to https://quill.p3k.io and entering your server.
