### ISSUE TITLE
ActivityPub API

### ISSUE THREAD

**Issue by TomboFry** [TomboFry/microlight#6]
This means that people are able to perform likes, replies, and mentions using their own website. See [reply](https://indieweb.org/reply), [webmentions](https://indieweb.org/Webmention), [likes](https://indieweb.org/like), and more.

**Comment by TomboFry** [comment]
While this is still an important feature that will get added, I'm not going to include it in the very first version/release, as there are more important things I would like to work on first, so I am removing it from the "initial release" milestone.

**Comment by pwFoo** [comment]
Witch ActivityPub API microlight would be compatible to mastodon, right?

**Comment by TomboFry** [comment]
Unfortunately, I have come to the conclusion that native support for ActivityPub is outside the scope of Microlight. Of course, it would be very nice to have it, although it would much better suited to support some kind of [bridge](https://indieweb.org/bridge) between the two standards.

The reason for this is purely to keep Microlight as lightweight as possible. It is not meant to be a large or complex piece of software, really.
