### ISSUE TITLE
Question about microlight / activitypub

### ISSUE THREAD

**Issue by pwFoo** [TomboFry/microlight#8]
At the moment I try some social networks like Mastodon, Friendica or Diaspora with decentralized instances. 

Would it possible with microlight to build such a site / server / instance? And communicate with other instances like Mastodon via activitypub / ostatus protocols?

I mean prepare local data to be send / received / shared to networks?

**Comment by pwFoo** [comment]
Would bei nice to integrate such a feature into the used cmf, but it looks complicated and no lib / class ist available.

**Comment by TomboFry** [comment]
Hello! Microlight will be intended as a simple blog engine for a single person. It is not intended for use as a social network where multiple people sign up, if that is what you are referring to.

I need to do more research, but I would like it to support [POSSE](https://indieweb.org/POSSE), where it will automatically post to other social media websites. That way, people's likes, comments, and reposts will show up on the original post.

**Comment by pwFoo** [comment]
Maybe interesting to use it with my preferred php cmf. Thanks

**Comment by m4sk1n** [comment]
@TomboFry, there is already single-user software using ActivityPub

**Comment by TomboFry** [comment]
Just to clarify, this will not be oriented around ActivityPub specifically. This project is essentially a remake of another project of mine called "[hyperlight](https://github.com/TomboFry/hyperlight)" (which was a super simple blog engine based on markdown files), except this project will make use of MicroPub (hence the name "*micro*light"), different post formats, and other IndieWeb features.

To be honest I wasn't expecting people to pay attention to this project so soon, absolutely nothing about this is properly fleshed out yet 😅

**Comment by TomboFry** [comment]
After doing some more research, I will *definitely* be adding ActivityPub support, so people can follow your blog on (for example) Mastodon, and like and comment on your posts straight from there. I'm not sure about doing it the other way around (ie. Liking other people's posts from your website), but that doesn't make sense from a UI point of view, but I'm sure I'll figure something out.
